In [1]:
import numpy as np

In [6]:
print(np.__version__)
print(np.show_config)

1.20.3
<function show at 0x000000217FEA85E0>


In [7]:
a=np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a=np.zeros(10)
print(a.size)
print(a.itemsize)

10
8


In [10]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x000000217EE5F4F0>, toplevel='numpy')>

In [12]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
a=np.arange(10,50)
reverse=a[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [22]:
a=np.arange(0,9)
b=a.reshape((3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
a=np.array([1,2,0,0,4,0])
b=np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


In [24]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
np.random.random((3,3,3))

array([[[0.09460519, 0.82924907, 0.69161445],
        [0.85809186, 0.28804383, 0.03864018],
        [0.96277228, 0.271714  , 0.18373423]],

       [[0.6423316 , 0.62986293, 0.95424297],
        [0.3311404 , 0.89720493, 0.66559462],
        [0.98012107, 0.78549692, 0.24446065]],

       [[0.15527454, 0.61323942, 0.98697972],
        [0.39002056, 0.65657851, 0.75833294],
        [0.48609809, 0.48564966, 0.72757537]]])

In [29]:
a=np.random.random((3,3,3))
print(np.min(a))
print(np.max(a))

0.008548840455786522
0.9181906580034037


In [30]:
a=np.random.random(30)
print(np.mean(a))

0.44721111599714064


In [38]:
a=np.ones((3,3))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [41]:
a=np.ones((3,3))
a[1:-1,1:-1]=0
b=np.pad(a,pad_width=1)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
np.NAN

nan

In [45]:
np.inf

inf

In [49]:
a = np.diag(np.arange(1,5),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [50]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [53]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [54]:
a=np.array([0,1])
print(np.tile(a,(8,8)))

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [57]:
a=np.random.randint(5,100,size=(5,5))
a_max,a_min=a.max(),a.min()
norm=(a-a_max)/(a_max-a_min)
print(norm)


[[-0.23333333 -0.92222222 -0.57777778 -0.34444444 -0.65555556]
 [-0.23333333 -1.         -0.52222222 -0.36666667 -0.86666667]
 [-0.57777778 -0.55555556 -0.65555556 -0.35555556 -0.44444444]
 [-0.26666667 -0.43333333 -0.33333333 -0.28888889 -0.07777778]
 [-0.5        -0.26666667 -0.2        -0.54444444  0.        ]]


In [58]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_2420/2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [62]:
a=np.random.randint(5,100,size=(5,3))
b=np.random.randint(5,100,size=(3,2))
c=np.matmul(a,b)
print(c)

[[ 5331  2960]
 [ 8572  6565]
 [10500  7966]
 [ 6167  5985]
 [ 2110  1347]]


In [63]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [76]:
a=np.arange(1,15)
a[(3<a) & (a<=8)]*=-1
print(a)

[ 1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


In [77]:
a=np.arange(1,15)
b=np.sum(a)
print(b)

105


In [79]:
Z=np.array([1,2,3,4])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([1., 2., 3., 4.])

In [80]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Lenovo\AppData\Local\Temp/ipykernel_2420/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Lenovo\AppData\Local\Temp/ipykernel_2420/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [82]:
a = np.random.uniform(-10,+10,10)
print(a)
print (np.copysign(np.ceil(np.abs(a)), a))

[-8.94593447 -7.37570079 -1.58204309  3.44475043  5.24786468  2.97217838
 -5.04871474  3.53278919  6.14701614 -1.54315259]
[-9. -8. -2.  4.  6.  3. -6.  4.  7. -2.]


In [83]:
ar1 = np.array([9, 12, 15, 7, 12, 9])
ar2 = [1, 5, 9, 7, 9]
  
# Common values between two arrays
print(np.intersect1d(ar1, ar2))

[7 9]


In [84]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [91]:
today = np.datetime64('today')
print(today)
yest=np.datetime64('today')-np.timedelta64(1)
print(yest)
tomo=np.datetime64('today')+np.timedelta64(1)
print(tomo)

2022-09-30
2022-09-29
2022-10-01


In [95]:
t = np.arange(np.datetime64("2016-07-01"),np.datetime64("2016-07-31"))
print(t)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30']


In [98]:
A = np.ones(3)*1
B = np.ones(3)*1
C = np.ones(3)*1
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1., -1., -1.])

In [99]:
a = np.random.uniform(0,10,10)

print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[6. 5. 7. 7. 4. 8. 1. 4. 1. 4.]
[6. 5. 7. 7. 4. 8. 1. 4. 1. 4.]
[6. 5. 7. 7. 4. 8. 1. 4. 1. 4.]
[6 5 7 7 4 8 1 4 1 4]
[6. 5. 7. 7. 4. 8. 1. 4. 1. 4.]


In [101]:
np.random.randint(0,5,size=(5,5))

array([[0, 4, 0, 3, 4],
       [3, 0, 0, 0, 0],
       [2, 1, 0, 2, 3],
       [1, 1, 2, 1, 4],
       [0, 1, 2, 2, 4]])

In [104]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [106]:
np.random.randint(0,10,size=10)

array([1, 1, 7, 2, 4, 0, 9, 2, 6, 5])

In [109]:
a=np.random.randint(0,10,size=10)
a.sort()
print(a)

[2 2 2 2 4 5 5 7 8 9]


In [111]:
a = np.arange(10)
b = np.add.reduce(a)
print(b)

45


In [114]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
c=np.allclose(a,b)
print(c)
c1=np.array_equal(a,b)
print(c1)

False
False


In [116]:
a = np.random.randint(0,10,10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [117]:
a= np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.07720335 0.81433834 1.12464665 0.4761314  0.7066913  0.57669556
 1.27247414 0.52812408 0.54410149 0.82264406]
[0.47944665 1.36551655 0.95734673 1.27514032 0.61339933 1.42409186
 0.76341242 1.34280195 0.93002209 0.7459318 ]


In [121]:
a = np.random.randint(0,10,10)
a[a.argmax()] = 0
print(a)

[5 1 8 0 0 6 5 4 8 2]


In [122]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [123]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [124]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [127]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

28


In [128]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Lenovo\AppData\Local\Temp/ipykernel_2420/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [129]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.99347728 0.07154882 0.20271357 0.06642875 0.30001422
  0.74480345 0.97893986 0.40751911 0.36045962]
 [0.99347728 0.         0.99844488 0.84346376 1.03377906 0.74004288
  0.34824609 0.17201985 0.66681512 0.78653209]
 [0.07154882 0.99844488 0.         0.17047406 0.04054293 0.34079326
  0.77017717 0.9961521  0.44847646 0.31500195]
 [0.20271357 0.84346376 0.17047406 0.         0.2107413  0.28417416
  0.64831966 0.85707249 0.37811653 0.16191557]
 [0.06642875 1.03377906 0.04054293 0.2107413  0.         0.36056311
  0.79828916 1.02761811 0.46848436 0.35492131]
 [0.30001422 0.74004288 0.34079326 0.28417416 0.36056311 0.
  0.45406548 0.69845713 0.10794086 0.39719285]
 [0.74480345 0.34824609 0.77017717 0.64831966 0.79828916 0.45406548
  0.         0.25236747 0.35853877 0.65901852]
 [0.97893986 0.17201985 0.9961521  0.85707249 1.02761811 0.69845713
  0.25236747 0.         0.60825319 0.83213043]
 [0.40751911 0.66681512 0.44847646 0.37811653 0.46848436 0.10794086
  0.35853877 0.60825

In [130]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [131]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [132]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0